name: Pipeline Python template

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo in runner
        uses: actions/checkout@v2          
      - name: Setup environment
        run: |
          echo "Downloading the python dependencies"
          pip install --no-cache-dir -r requirements.txt
          echo "Raising the server"
          uvicorn app.business.app:app --reload &
          sleep 5
          echo "Server ready for requests"
          curl --version
          curl -X POST http://127.0.0.1:8000
          
#  -data '{"msg": "seed python"}' -H 'Ce-Id: 536808d3-88be-4077-9d7a-a3f162705f79' 'Ce-specversion: 0.3' -H 'Ce-Type: dev.knative.samples.helloworld' -H 'Ce-Source: dev.knative.samples/helloworldsource' -H 'Content-Type: application/json' http://127.0.0.1:8000/

  # cd: 
  #   runs-on: windows-latest
  #   needs: ["ci"]
  #   steps:
  #     - name: Create docker image
  #       run: echo "Generadno la imagen de docker"
  
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: ["cd"]
  #   steps:
  #     - name: Deploy image to knative
  #       run: echo "Desplegando imagen"

                                                       