name: Pipeline Python template

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo in runner
        uses: actions/checkout@v2          
      - name: Setup environment
        run: |
          echo "Downloading the python dependencies"
          pip install --no-cache-dir -r requirements.txt
          echo "Raising the server"
          uvicorn app.business.app:app --reload &
          sleep 10
          echo "Server ready for requests"

  # cd: 
  #   runs-on: windows-latest
  #   needs: ["ci"]
  #   steps:
  #     - name: Create docker image
  #       run: echo "Generadno la imagen de docker"
  
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: ["cd"]
  #   steps:
  #     - name: Deploy image to knative
  #       run: echo "Desplegando imagen"

                                                       