name: Pipeline Python template

on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo in runner
        uses: actions/checkout@v2          
      - name: Setup environment
        run: |
          echo "Downloading the python dependencies"
          pip install --no-cache-dir -r requirements.txt
          echo "Raising the server"
          uvicorn app.business.app:app --reload --port 9017 &
          sleep 5
          echo "Server ready for requests"
          curl -X POST --header 'Ce-Id: 536808d3-88be-4077-9d7a-a3f162705f79' --header 'Ce-specversion: 0.3' --header 'Ce-Type: dev.knative.samples.helloworld' --header 'Ce-Source: dev.knative.samples/helloworldsource' --header 'Content-Type: application/json' -d '{"msg": "seed python"}' -v 'localhost:9017'

  unit-test:
    runs-on: ubuntu-latest
    needs: ["ci"]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Unit test
        run: |
          pip install --no-cache-dir -r requirements.txt
          echo "Unit test"
          coverage run -m unittest discover


  build-and-upload-image:
    runs-on: ubuntu-latest
    needs: ["unit-test"]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY}}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


          
