name: Pipeline Python template

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Copy project
        uses: actions/checkout@v2          
      - name: Unit test
        run: |
          pwd
          ls -a
  # cd: 
  #   runs-on: windows-latest
  #   needs: ["ci"]
  #   steps:
  #     - name: Create docker image
  #       run: echo "Generadno la imagen de docker"
  
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: ["cd"]
  #   steps:
  #     - name: Deploy image to knative
  #       run: echo "Desplegando imagen"

                                                       